version: "2"

services:
  web:
    build: .
    container_name: web
    environment:
      DJANGO_SETTINGS_MODULE: razvitie.settings_prod
      DATABASE_URL: postgres://postgres:Ghbdtn11@@db/demo
      ALLOWED_HOSTS: "*"
    ports:
      - "80:80"

  db:
    image: postgres:9.5
    environment:
      POSTGRES_PASSWORD: "Ghbdtn11@"
      POSTGRES_DB: "demo"
    volumes:
      - /var/lib/postgresql/data
